CREATE DATABASE QLSV;
GO
USE QLSV;
GO

-- Bảng KHOA
CREATE TABLE KHOA (
    MaKhoa VARCHAR(10) PRIMARY KEY,
    TenKhoa NVARCHAR(100) NOT NULL UNIQUE,
    Email NVARCHAR(100),
    DienThoai VARCHAR(20)
);

-- Bảng LOP
CREATE TABLE LOP (
    MaLop VARCHAR(10) PRIMARY KEY,
    TenLop NVARCHAR(100) NOT NULL,
    MaKhoa VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES KHOA(MaKhoa)
);

-- Bảng SINHVIEN
CREATE TABLE SINHVIEN (
    MaSV VARCHAR(15) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE NOT NULL,
    GioiTinh CHAR(1) NOT NULL CHECK (GioiTinh IN ('M','F','O')),
    Email NVARCHAR(120) UNIQUE,
    DienThoai VARCHAR(20),
    DiaChi NVARCHAR(255),
    MaLop VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES LOP(MaLop)
);

-- Bảng MONHOC
CREATE TABLE MONHOC (
    MaMH VARCHAR(10) PRIMARY KEY,
    TenMH NVARCHAR(150) NOT NULL,
    SoTinChi INT NOT NULL CHECK (SoTinChi >= 0),
    MaKhoa VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES KHOA(MaKhoa)
);

-- Bảng DANGKY
CREATE TABLE DANGKY (
    MaSV VARCHAR(15) NOT NULL,
    MaMH VARCHAR(10) NOT NULL,
    HocKy TINYINT NOT NULL CHECK (HocKy IN (1,2,3)),
    NamHoc SMALLINT NOT NULL,
    NgayDangKy DATE DEFAULT GETDATE(),
    PRIMARY KEY (MaSV, MaMH, HocKy, NamHoc),
    FOREIGN KEY (MaSV) REFERENCES SINHVIEN(MaSV) ON DELETE CASCADE,
    FOREIGN KEY (MaMH) REFERENCES MONHOC(MaMH) ON DELETE CASCADE
);

-- Bảng DIEM
CREATE TABLE DIEM (
    MaSV VARCHAR(15) NOT NULL,
    MaMH VARCHAR(10) NOT NULL,
    HocKy TINYINT NOT NULL,
    NamHoc SMALLINT NOT NULL,
    DiemQT DECIMAL(4,2) DEFAULT 0 CHECK (DiemQT BETWEEN 0 AND 10),
    DiemThi DECIMAL(4,2) DEFAULT 0 CHECK (DiemThi BETWEEN 0 AND 10),
    DiemTongKet DECIMAL(4,2) CHECK (DiemTongKet BETWEEN 0 AND 10),
    TrangThai NVARCHAR(20) DEFAULT 'Đang học',
    PRIMARY KEY (MaSV, MaMH, HocKy, NamHoc),
    FOREIGN KEY (MaSV, MaMH, HocKy, NamHoc) REFERENCES DANGKY(MaSV, MaMH, HocKy, NamHoc) ON DELETE CASCADE
);
